# Generated by Django 4.2.2 on 2023-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAdress',
            new_name='UserAddress',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='poster_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
